### ISSUE TITLE
Forgot to compile parseQuery.get method from cs to js?

### ISSUE THREAD

**Issue by norman784** [felipesabino/angular-parse#2]
Seems that en cs there is a get method but in the js don't.

Regards

**Comment by norman784** [comment]
nice

**Comment by felipesabino** [comment]
@norman784 sorry for the delay, I just realised I wasn't _watching_ my own repo and didn't get any notifications :astonished:

**Comment by norman784** [comment]
don't worry I added it by hand when I used it..
